name: Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Bump tag type: major, minor, patch. default: minor"
        required: true
        default: "minor"
permissions: write-all
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Check out code
        uses: actions/checkout@v4

      - name: Bump tag version
        id: bumpTag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: "${{ github.event.inputs.bump_type }}"
      - name: Bump tag locally
        run: git tag ${{ steps.bumpTag.outputs.new_tag }}

      - name: Set environment variables
        run: |
          echo "GOLANG_VERSION=$(go version)" >> $GITHUB_ENV
          echo "BUILT_BY=$(whoami)@$(hostname)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # GoReleaser will take care of publishing those artifacts into the release
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOLANG_VERSION: ${{ env.GOLANG_VERSION }}
          BUILT_BY: ${{ env.BUILT_BY }}
